# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "firewire_ohci" "usbhid" "usb_storage" "zfs" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "tank/nixos";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/f94f2298-a1e0-4d0b-b744-bced4ae352c3";
      fsType = "ext2";
    };

  fileSystems."/home" =
    { device = "tank/home";
      fsType = "zfs";
    };

  swapDevices = [ { label = "SWAP"; } ];

  nix.maxJobs = 4;
}
